---

- shell: echo {{ item }} hold | dpkg --set-selections
  with_items:
    - udev
    - initscripts
    - upstart

- command: dpkg-divert --local --rename --add {{ item }}
  with_items: box_container_replace

- file:
    src: "/bin/true"
    dest: "{{ item }}"
    owner: root
    group: root
    force: yes
    state: link
  with_items: box_container_replace


- file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - "/etc/my_init.d"
    - "/etc/container_environment"

- copy:
    src: my_init
    dest: /sbin/my_init
    owner: root
    group: root
    mode: 0755

- name: create TERM env
  lineinfile:
    create: yes
    state: present
    dest: /etc/container_environment/TERM
    line: dumb
