---

- shell: echo {{ item }} hold | dpkg --set-selections
  with_items:
    - udev
    - initscripts
    - upstart

- command: dpkg-divert --local --rename --add {{ item }}
  with_items: box_container_replace

- file:
    src: "/bin/true"
    dest: "{{ item }}"
    owner: root
    group: root
    force: yes
    state: link
  with_items: box_container_replace


- file:
    path: "/etc/container_environment"
    owner: root
    group: root
    state: directory

- copy:
    src: my_init
    dest: /sbin/my_init
    owner: root
    group: root
    mode: 755

