---

- name: Locale | Copy configuration
  template:
    src: locale/locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644

- name: Locale | generate locale
  command: "locale-gen {{ box_locale }}"

- name: reconfigure locales
  command: dpkg-reconfigure --frontend noninteractive locales
