---

- name: copy locale
  copy:
    src: misc/locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
  register: locale

- name: reconfigure locales
  command: dpkg-reconfigure --frontend noninteractive locales
  when: locale.changed

