---
  - include: apt.yml

  - include: timezone.yml

  - include: locales.yml

  - include: update.yml
    when: box_upgrade

  - include: basic.yml

  - include: github.yml
    when: box_github_https

  - include: user.yml

  - include: ruby.yml
    when: "{{ box_ruby_supported | intersect(box_packages)| length == 1 }}"

  - include: nodejs.yml
    when: "'nodejs' in box_packages"

  - include: redis.yml
    when: "'redis' in box_packages"

  - include: nginx.yml
    when: "'nginx' in box_packages"

  - include: passenger.yml
    when: "'passenger' in box_packages"

  - include: memcached.yml
    when: "'memcached' in box_packages"

  - include: container.yml
    when: box_container
