---
  - include: apt.yml

  - include: timezone.yml

  - include: locales.yml

  - include: update.yml
    when: box_upgrade

  - include: basic.yml

  - include: github.yml
    when: box_github_https

  - include: user.yml

  - include: ruby.yml
    when: "{{ box_ruby_supported | intersect({{box_essential}})| length == 1 }}"

  - include: nodejs.yml
    when: "'nodejs' in {{box_essential}}"

  - include: redis.yml
    when: "'redis' in {{box_essential}}"

  - include: nginx.yml
    when: "'nginx' in {{box_essential}}"

  - include: passenger.yml
    when: "'passenger' in {{box_essential}}"

  - include: memcached.yml
    when: "'memcached' in {{box_essential}}"

  - include: container.yml
    when: box_container
