---

- name: Nginx | add oficial repository
  apt_repository:
    repo: 'ppa:nginx/stable'
    update_cache: yes

- name: Nginx | Install nginx
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  with_items:
   - "{% if 'passenger' in box_packages %}nginx-extras{% else %}nginx{% endif %}"

- name: Nginx | Nginx directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - /etc/nginx/main.d
    - /etc/nginx/conf.d
    - /etc/nginx/sites-enabled

- name: Nginx | Nginx configuration
  template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Nginx | Nginx default site configuration
  template:
    src: nginx/default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0644

- name: Nginx | Nginx environment configuration
  copy:
    src: nginx/environment.conf
    dest: /etc/nginx/main.d/environment.conf
    owner: root
    group: root
    mode: 0644

- name: Nginx | link logs files
  file:
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
    state: link
    force: yes
  with_items:
    - [ "/dev/stdout", "/var/log/nginx/access.log" ]
    - [ "/dev/stderr", "/var/log/nginx/error.log" ]
  when: box_container
