---

- name: Install nginx
  apt:
   pkg: "{{ item }}"
   state: installed
   update_cache: yes
   cache_valid_time: 3600
  with_items:
   - "{% if 'passenger' in box_packages %}nginx-extras{% else %}nginx{% endif %}"

- name: Nginx directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - /etc/nginx/main.d
    - /etc/nginx/conf.d
    - /etc/nginx/sites-enabled

- name: Nginx configuration
  template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Nginx default site configuration
  template:
    src: nginx/default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0644

- name: Nginx environment configuration
  copy:
    src: nginx/environment.conf
    dest: /etc/nginx/main.d/environment.conf
    owner: root
    group: root
    mode: 0644

- name: Nginx passenger configuration
  copy:
    src: nginx/passenger.conf
    dest: /etc/nginx/conf.d/passenger.conf
    owner: root
    group: root
    mode: 0644
  when: "'passenger' in box_packages"


- { include: runit.yml, runit_scripts: [ "nginx", "nginx-log-forwarder" ], when: box_container }
