---

- name: Passenger | Import GPG key into apt
  apt_key:
   keyserver: keyserver.ubuntu.com
   id: 561F9B9CAC40B2F7
   state: present

- name: Passenger | Install
  apt:
   pkg: apt-transport-https
   state: installed
   update_cache: yes
   cache_valid_time: 3600

- name: Passenger | Add deb repository
  apt_repository:
   repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main'
   state: present

- name: Passenger | Install
  apt:
   pkg: "{{ item }}"
   state: installed
   update_cache: yes
   install_recommends: yes
  with_items:
   - passenger

- name: Passenger | Fix passenger utils shebang
  lineinfile:
    dest: "{{ item }}"
    regexp: '^#\!/usr/bin/ruby\s*'
    line: "#!/usr/bin/env ruby"
    backrefs: yes
    state: present
  with_items:
    - "/usr/sbin/passenger-memory-stats"
    - "/usr/sbin/passenger-status"

- name: Passenger | Compile native support
  command: passenger-config build-native-support

- name: Nginx passenger configuration
  copy:
    src: nginx/passenger.conf
    dest: /etc/nginx/conf.d/passenger.conf
    owner: root
    group: root
    mode: 0644
  when: "'nginx' in box_packages"
