---

- name: Runit | Install
  apt:
   pkg: "runit"
   state: installed
   update_cache: yes
   cache_valid_time: 3600

- name: Runit | base directory
  file:
   path: /etc/service
   owner: root
   group: root
   state: directory

- name: "Runit | create service"
  file:
   path: "/etc/service/{{ item }}"
   owner: root
   group: root
   state: directory
  with_items: runit_scripts

- file:
   path: "/etc/service/{{ item }}/down"
   owner: root
   group: root
   state: touch
  with_items: runit_scripts

- name: "Runit | creating script"
  copy:
   src: "runit/{{ item }}"
   dest: "/etc/service/{{ item }}/run"
   owner: root
   group: root
   mode: 0755
  with_items: runit_scripts

